BASE: ['']
TOOLBOX_MODE: "only_test"      # "train_and_test"  or "only_test"
TRAIN:
  MODEL_FILE_NAME: CMBP_PURE_PHYSFORMER
TEST:
  METRICS: ['MAE','RMSE','MAPE','Pearson']
  USE_LAST_EPOCH: True # to use provided validation dataset to find the best epoch, should be false
  DATA:
    FS: 30
    DATASET: PURE
    DO_PREPROCESS: False # if first time, should be true
    DATA_FORMAT: NDHWC
    DATA_PATH: "/data/rppg_14_pure_video_nt_lab/raw/PURE/"                     # Raw dataset path, need to be updated
#    CACHED_PATH: "/data/rppg_14_pure_video_nt_lab/processed/"    # Processed dataset save path, need to be updated
    CACHED_PATH: "/vol/rPPG/physformerData/"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS:
      DATA_TYPE: [ 'Raw']
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 160
      CROP_FACE:
        DO_CROP_FACE: True
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 1
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 128
        W: 128
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
EARLY_STOPPING:
  PATIENCE: 10
  DELTA: 0.01
  TRAIN: False
  VALID: False
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.1
  NAME: PhysFormer
  PHYSFORMER:                     # Probably need to update these in some meaningful way
    PATCH_SIZE: 4
    DIM: 96
    FF_DIM: 144
    NUM_HEADS: 4
    NUM_LAYERS: 12
    THETA: 0.7
  MODEL_DIR: "/data/rppg_23_bi_video_nt_lab/processed/Models/"    # Processed dataset save path, need to be updated
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: "Welch"        # "FFT" or "peak detection"
  MODEL_PATH: "/data/rppg_23_bi_video_nt_lab/processed/Models/CMBP_SizeW128_SizeH128_ClipLength160_DataTypeRaw_DataAugNone_LabelTypeStandardized_Crop_faceTrue_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len1_Median_face_boxFalse/last-v1.ckpt"
