BASE: ['']
TOOLBOX_MODE: "only_test"      # "train_and_test"  or "only_test"
TRAIN:
  MODEL_FILE_NAME: VIPL_TSCAN_V3_SMALLER
TEST:
  METRICS: ['MAE','RMSE','MAPE','Pearson', 'SNR']
  USE_LAST_EPOCH: True
  OUT_SAVE_DIR: "/homes/bacharya/rPPG-Toolbox/DST_results/TS-CAN/"
  DATA:
    FS: 25
    DATASET: DST
    DO_PREPROCESS: True  # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/data/dst_tsst_22_bi_multi_nt_lab/processed/sensor_files.json"                     # Raw dataset path, need to be updated
#    CACHED_PATH: "/data/dst_tsst_22_bi_multi_nt_lab/processed/rPPG"    # Processed dataset save path, need to be updated
    CACHED_PATH : "/homes/bacharya/rPPG-Toolbox/DST_results/TS-CAN/"
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS:
      DATA_TYPE: [ 'DiffNormalized','Standardized' ]
      LABEL_TYPE:  Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 2000
      CROP_FACE:
        DO_CROP_FACE: False
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: True
          DYNAMIC_DETECTION_FREQUENCY : 1
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.2
  NAME: Tscan
  TSCAN:
    FRAME_DEPTH: 10
INFERENCE:
  BATCH_SIZE: 1
  EVALUATION_METHOD: "Welch" # "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: True # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 30 # In seconds
  MODEL_PATH: "/homes/bacharya/rPPG-Toolbox/DST_results/TS-CAN/VIPL_SizeW72_SizeH72_ClipLength900_DataTypeDiffNormalized_Standardized_DataAugNone_LabelTypeStandardized_Crop_faceFalse_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len30_Median_face_boxFalse/VIPL_PURE_DST_epoch=38.ckpt"
